# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'toca_social_dw'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

vars:
#Booking system switch date
  switch_date: to_date('2024-01-18')

seeds:
  toca-social-dw:
    +database: BASE
    +schema: Inputs

models:
  toca-social-dw:
    base:
      +database: "{% if target.name == 'dev' %}base_dev{% elif target.name == 'UAT' %}base_uat{% elif target.name == 'prod' %}base_prod{% else %}invalid_database{% endif %}"
      +materialized: view
      sevenrooms:
        +schema: "sevenrooms"
      people_counter:
        +schema: "people_counter"

    intermediate:
      +database: "{% if target.name == 'dev' %}dw_dev{% elif target.name == 'UAT' %}dw_uat{% elif target.name == 'prod' %}dw_prod{% else %}invalid_database{% endif %}"
      +materialized: table
      intermediate:
        +schema: "intermediate"     

    marts:
      +database: "{% if target.name == 'dev' %}dw_dev{% elif target.name == 'UAT' %}dw_uat{% elif target.name == 'prod' %}dw_prod{% else %}invalid_database{% endif %}"
      core:
        materialized: table
        schema: CORE

    replicate:
        +materialized: TOCA_DATA_REPLICATION
        +database: "dw_prod"
        +schema: sevenrooms

    staging:
      +database: "{% if target.name == 'dev' %}base_dev{% elif target.name == 'UAT' %}base_uat{% elif target.name == 'prod' %}base{% else %}invalid_database{% endif %}"
      +materialized: view
      bookings:
        +schema: "bookings"
      budget:
        +schema: "budget"
      epos:
        +schema: "epos"
      gaming:
        +schema: "gaming"
      inputs:
        +schema: "inputs"
      people_counter:
        +schema: "people_counter"
      sentiment:
        +schema: "sentiment"
      sevenrooms:
        +schema: "sevenrooms"
        +materialized: table
      stripe:
        +schema: "stripe"                                                                