with
    cte_source as (select * from {{ source("stripe", "charge") }}),

    cte_main as (
        select

            to_date(to_timestamp_tz(created)) as Created_date,
            to_time(to_timestamp_tz(created)) as Created_time,
            id as charge_transaction_id,
            balance_transaction_id,
            payment_intent_id,
            payment_method_id,
            calculated_statement_descriptor,
            captured,
            currency,
            disputed,
            livemode,
            metadata_total_inc_vat,
            metadata_price_inc_vat,
            metadata_vat,
            metadata_booking_ref,
            metadata_session_id,
            metadata_subtotal_ex_vat,
            metadata_total_pp,
            outcome_network_status,
            outcome_risk_level,
            outcome_risk_score,
            outcome_seller_message,
            outcome_type,
            paid,
            payment_intent,
            receipt_url,
            refunded,
            status,
            failure_code,
            failure_message,
            outcome_reason,
            fraud_details_stripe_report,
            outcome_rule,
            application,
            description,
            metadata_crm_deal_id,
            metadata_fee_total,
            metadata_stripe_user_id,
            metadata_spayment_due,
            metadata_crm_contact_id,
            metadata_spayment_auto_charge,
            metadata_fee_amount,
            metadata_account_id,
            metadata_fee_label,
            metadata_spayment_id,
            metadata_fee_payment_type,
            metadata_invoice_number,
            customer_id,
            statement_descriptor,
            metadata__tripleseat__u_r_l,
            metadata__tripleseat__location__i_d,
            metadata__tripleseat__location,
            metadata__tripleseat__payment__i_d,
            authorization_code,
            metadata_crm_org_id,
            fraud_details_user_report,
            metadata_promocode,
            metadata_discount_inc_vat,
            receipt_number,
            metadata_pc_initiated,
            amount / 100 as amount,
            amount_captured / 100 as amount_captured,
            amount_refunded / 100 as amount_refunded,
            application_fee_amount / 100 as application_fee_amount
        from cte_source as c
    )

select *
from cte_main
